name: GolangCI-lint

on:
  pull_request:
    branches:
      - "main"
    types: [ opened, synchronize ]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:

      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run linters
        uses: golangci/golangci-lint-action@ec5d18412c0aeab7936cb16880d708ba2a64e1ae # v6.2.0
        with:
          version: latest
